### ISSUE TITLE
Wrong Github clone command

### ISSUE THREAD

**Issue by TrevorBurnham** [jaz303/boxy#4]
For those of us who aren't commiters to the Boxy repo, the clone command given in the README and at http://onehackoranother.com/projects/jquery/boxy/ should be changed from

```
git clone git@github.com:jaz303/boxy.git
```

to

```
git clone git://github.com/jaz303/boxy.git
```

It's a common mistake. :) By the way, should this project be considered "active"? Has it been tested for jQuery 1.4 compatibility?

**Comment by jaz303** [comment]
It has not been tested on 1.4 yet. However I've just started work on a new project at work that will use Boxy extensively so despite the lack of recent commits the project is very much alive.
